### ISSUE TITLE
error

### ISSUE THREAD

**Issue by kiruhasas22** [MatusOllah/gophengine#1]
mkdir -p ./bin/windows-amd64
go get
make: go: No such file or directory
make: *** [Makefile:18: build] Error 127

**Comment by MatusOllah** [comment]
You need to install Go and a C compiler
https://ebitengine.org/en/documents/install.html

**Comment by MatusOllah** [comment]
also on Windows you don't need a C compiler

**Comment by kiruhasas22** [comment]
> You need to install Go and a C compiler https://ebitengine.org/en/documents/install.html

so I have GO installed

**Comment by MatusOllah** [comment]
now run ```make clean && make```
